# Site settings
title: umd.io
email: hi@umd.io
description: > # this means to ignore newlines until "baseurl:"
  An API for the University of Maryland.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://umd.io" # the base hostname & protocol for your site
github_username: umdio
permalink: none

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
source: src
destination: public
sass:
  sass_dir: _sass
  style: compressed
highlighter: rouge

# Server settings
host: 0.0.0.0
